
const monthNames = ["january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"];

const critterNames = ["Bitterling","Pale Chub","Crucian Carp","Dace","Carp","Koi","Goldfish","Pop-eyed Goldfish","Ranchu Goldfish","Killifish","Crawfish","Soft-shelled Turtle","Snapping Turtle",
"Tadpole","Frog","Freshwater Goby","Loach","Catfish","Giant Snakehead","Bluegill","Yellow Perch","Black Bass","Tilapia","Pike","Pond Smelt","Sweetfish","Cherry Salmon","Char",
"Golden Trout","Stringfish","Salmon","King Salmon","Mitten Crab","Guppy","Nibble Fish","Angelfish","Betta","Neon Tetra","Rainbowfish","Piranha","Arowana","Dorado","Gar",
"Arapaima","Saddled Bichir","Sturgeon","Sea Butterfly","Sea Horse","Clown Fish","Surgeonfish","Butterfly Fish","Napoleonfish","Zebra Turkeyfish","Blowfish","Puffer Fish","Anchovy",
"Horse Mackerel","Barred Knifejaw","Sea Bass","Red Snapper","Dab","Olive Flounder","Squid","Moray Eel","Ribbon Eel","Tuna","Blue Marlin ","Giant Trevally","Mahi-mahi","Ocean Sunfish",
"Ray","Saw Shark","Hammerhead Shark","Great White Shark","Whale Shark","Suckerfish","Football Fish","Oarfish","Barreleye","Coelacanth","Common Butterfly","Yellow Butterfly","Tiger Butterfly",
"Peacock Butterfly","Common Bluebottle","Paper Kite Butterfly","Great Purple Emperor","Monarch Butterfly","Emperor Butterfly ","Agrias Butterfly","Rajah Brooke's Birdwing","Queen Alexandra's Birdwing",
"Moth","Atlas Moth","Madagascan Sunset Moth","Long Locust","Migratory Locust","Rice Grasshopper","Grasshopper","Cricket","Bell Cricket","Mantis","Orchid Mantis","Honeybee","Wasp",
"Brown Cicada","Robust Cicada","Giant Cicada","Walker Cicada","Evening Cicada","Cicada Shell","Red Dragonfly","Darner Dragonfly","Banded Dragonfly","Damselfly","Firefly","Mole Cricket",
"Pondskater","Diving Beetle","Giant Water Bug","Stinkbug","Man-faced Stink Bug","Ladybug","Tiger Beetle","Jewel Bettle","Violin Beetle","Citrus Long-horned Beetle","Rosalia Batesi Beetle",
"Blue Weevil Beetle","Earth-boring Dung Beetle","Dung Beetle","Scarab Beetle","Drone Beetle","Goliath Beetle","Saw Stag","Miyama Stag ","Giant Stag","Rainbow Stag","Cyclommatus Stag",
"Golden Stag","Giraffe Stag","Horned Dynastid","Horned Atlas","Horned Elephant","Horned Hercules","Walking Stick","Walking Leaf","Bagworm","Ant","Hermit Crab","Wharf Roach","Fly",
"Mosquito","Flea","Snail","Pill Bug","Centipede","Spider","Tarantula","Scorpion","Serene Painting","Warm Painting","Wistful Painting","Academic Painting","Graceful Painting","Calm Painting",
"Flowery Painting","Jolly Painting","Moody Painting","Famous Painting","Scary Painting","Dynamic Painting","Scenic Painting","Moving Painting","Amazing Painting","Quaint Painting",
"Solemn Painting","Basic Painting","Worthy Painting","Glowing Painting","Common Painting","Sinking Painting","Nice Painting","Proper Painting","Mysterious Painting","Twinkling Painting",
"Perfect Painting","Wild Painting Left Half","Wild Painting Right Half","Detailed Painting","Warrior Statue","Motherly Statue","Beautiful Statue","Familiar Statue","Robust Statue",
"Gallant Statue","Informative Statue","Rock-head Statue","Ancient Statue","Tremendous Statue","Valiant Statue","Mystic Statue","Great Statue","Red Rose","White Rose","Yellow Rose",
"Orange Rose","Black Rose","Pink Rose","Purple Rose","Blue Rose","Gold Rose","Red Tulip","White Tulip","Yellow Tulip","Orange Tulip","Black Tulip","Pink Tulip","Purple Tulip","Red Pansy",
"White Pansy","Yellow Pansy","Orange Pansy","Blue Pansy","Red(hybrid) Pansy","Purple Pansy","Red Cosmos","White Cosmos","Yellow Cosmos","Orange Cosmos","Pink Cosmos","Black Cosmos","Red Lily",
"White Lily","Yellow Lily","Orange Lily","Pink Lily","Black Lily","Red Hyacinth","White Hyacinth","Yellow Hyacinth","Orange Hyacinth","Pink Hyacinth","Purple Hyacinth","Blue Hyacinth",
"Red Windflower","White Windflower","Orange Windflower","Pink Windflower","Red(hybrid) Windflower","Purple Windflower","Blue Windflower","Red Mum","White Mum","Yellow Mum","Yellow(hybrid) Mum",
"Pink Mum","Purple Mum","Green Mum","Acanthostega","Amber","Ammonite","Anomalocaris","Archaeopteryx","Australopith","Coprolite","Dinosaur track","Dunkleosteus","Eusthenopteron","Juramaia",
"Myllokunmingia","Shark-tooth pattern","Trilobite","Ankylo skull","Ankylo torso","Ankylo tail","Archelon skull","Archelon tail","Brachio skull","Brachio chest","Brachio pelvis","Brachio tail",
"Deinony torso","Deinony tail","Dimetrodon skull","Dimetrodon torso","Diplo skull","Diplo neck","Diplo chest","Diplo pelvis","Diplo tail","Diplo tail tip","Iguanodon skull","Iguanodon torso",
"Iguanodon tail","Mammoth skull","Mammoth torso","Megacero skull","Megacero torso","Megacero tail","Left megalo side","Right megalo side","Ophthalmo skull","Ophthalmo torso","Pachy skull",
"Pachy tail","Parasaur skull","Parasaur torso","Parasaur tail","Plesio skull","Plesio tail","Plesio torso","Right ptera wing","Ptera body","Left ptera wing","Right quetzal wing","Quetzal torso",
"Left quetzal wing","Sabertooth skull","Sabertooth tail","Spino skull","Spino torso","Spino tail","Stego skull","Stego torso","Stego tail","Tricera skull","Tricera torso","Tricera tail",
"T. rex skull","T. rex torso","T. rex tail","Seaweed","Sea Grapes","Sea Cucumber","Sea Pig","Sea Star","Sea Urchin","Slate Pencil Urchin","Sea Anemone","Moon Jellyfish","Sea Slug","Pearl Oyster",
"Mussel","Oyster", "Scallop","Whelk","Turban Shell","Abalone","Gigas Giant Clam","Chambered Nautilus","Octopus","Umbrella Octopus","Vampire Squid","Firefly Squid","Gazami Crab","Dungeness Crab",
"Snow Crab","Red King Crab","Acorn Barnacle","Spider Crab","Tiger Prawn","Sweet Shrimp","Mantis Shrimp","Spiny Lobster","Lobster","Giant Isopod","Horseshoe Crab","Sea Pineapple","Spotted Garden Eel",
"Flatworm","Venus Flower Basket"];


const fishData = [
  {'name': "Bitterling", price: "900", location: "River", time: "All", month: "January, February, March, November, December", type:"Fish"},
  {'name': "Pale Chub", price: "200", location: "River", time: "9AM-4PM", month: "All", type:"Fish"},
  {'name': "Crucian Carp", price: "160", location: "River", time: "All", month: "All", type:"Fish"},
  {'name': "Dace", price: "240", location: "River", time: "4PM-9AM", month: "All", type:"Fish"},
  {'name': "Carp", price: "300", location: "Pond", time: "All", month: "All", type:"Fish"},
  {'name': "Koi", price: "4000", location: "Pond", time: "4PM-9AM", month: "All", type:"Fish"},
  {'name': "Goldfish", price: "1300", location: "Pond", time: "All", month: "All", type:"Fish"},
  {'name': "Pop-eyed Goldfish", price: "1300", location: "Pond", time: "9AM-4PM", month: "All", type:"Fish"},
  {'name': "Ranchu Goldfish", price: "4500", location: "Pond", time: "9AM-4PM", month: "All", type:"Fish"},
  {'name': "Killifish", price: "300", location: "Pond", time: "All", month: "April, May, June, July, August", type:"Fish"},
  {'name': "Crawfish", price: "200", location: "Pond", time: "All", month: "April, May, June, July, August, September", type:"Fish"},
  {'name': "Soft-shelled Turtle", price: "3750", location: "River", time: "4PM-9AM", month: "August, September", type:"Fish"},
  {'name': "Snapping Turtle", price: "5000", location: "River", time: "9PM-4AM", month: "April, May, June, July, August, September, October", type:"Fish"},
  {'name': "Tadpole", price: "100", location: "Pond", time: "All", month: "March, April, May, June, July", type:"Fish"},
  {'name': "Frog", price: "120", location: "Pond", time: "All", month: "May, June, July, August", type:"Fish"},
  {'name': "Freshwater Goby", price: "400", location: "River", time: "4PM-9AM", month: "All", type:"Fish"},
  {'name': "Loach", price: "400", location: "River", time: "All", month: "March, April, May", type:"Fish"},
  {'name': "Catfish", price: "800", location: "Pond", time: "4PM-9AM", month: "May, June, July, August, September, October", type:"Fish"},
  {'name': "Giant Snakehead", price: "5500", location: "Pond", time: "9AM-4PM", month: "June, July, August", type:"Fish"},
  {'name': "Bluegill", price: "180", location: "River", time: "9AM-4PM", month: "All", type:"Fish"},
  {'name': "Yellow Perch", price: "300", location: "River", time: "All", month: "January, February, March, October, November, December", type:"Fish"},
  {'name': "Black Bass", price: "400", location: "River", time: "All", month: "All", type:"Fish"},
  {'name': "Tilapia", price: "800", location: "River", time: "All", month: "June, July, August, September, October", type:"Fish"},
  {'name': "Pike", price: "1800", location: "River", time: "All", month: "September, October, November, December", type:"Fish"},
  {'name': "Pond Smelt", price: "500", location: "River", time: "All", month: "January, February, December", type:"Fish"},
  {'name': "Sweetfish", price: "900", location: "River", time: "All", month: "July, August, September", type:"Fish"},
  {'name': "Cherry Salmon", price: "1000", location: "River (clifftop)", time: "4PM-9AM", month: "March, April, May, June, September, October, November", type:"Fish"},
  {'name': "Char", price: "3800", location: "River (clifftop)", time: "4PM-9AM", month: "March, April, May, June, September, October, November", type:"Fish"},
  {'name': "Golden Trout", price: "15000", location: "River (clifftop)", time: "4PM-9AM", month: "March, April, May, September, October, November", type:"Fish"},
  {'name': "Stringfish", price: "15000", location: "River (clifftop)", time: "4PM-9AM", month: "January, February, March, December", type:"Fish"},
  {'name': "Salmon", price: "700", location: "River (mouth)", time: "All", month: "September", type:"Fish"},
  {'name': "King Salmon", price: "1800", location: "River (mouth)", time: "All", month: "September", type:"Fish"},
  {'name': "Mitten Crab", price: "2000", location: "River", time: "4PM-9AM", month: "September, October, November", type:"Fish"},
  {'name': "Guppy", price: "1300", location: "River", time: "9AM-4PM", month: "April, May, June, July, August, September, October, November", type:"Fish"},
  {'name': "Nibble Fish", price: "1500", location: "River", time: "9AM-4PM", month: "May, June, July, August, September", type:"Fish"},
  {'name': "Angelfish", price: "3000", location: "River", time: "4PM-9AM", month: "May, June, July, August, September, October", type:"Fish"},
  {'name': "Betta", price: "2500", location: "River", time: "9AM-4PM", month: "May, June, July, August, September, October", type:"Fish"},
  {'name': "Neon Tetra", price: "500", location: "River", time: "9AM-4PM", month: "April, May, June, July, August, September, October, November", type:"Fish"},
  {'name': "Rainbowfish", price: "800", location: "River", time: "9AM-4PM", month: "May, June, July, August, September, October", type:"Fish"},
  {'name': "Piranha", price: "2500", location: "River", time: "9AM-4PM, 9PM-4AM", month: "June, July, August, September", type:"Fish"},
  {'name': "Arowana", price: "10000", location: "River", time: "4PM-9AM", month: "June, July, August, September", type:"Fish"},
  {'name': "Dorado", price: "15000", location: "River", time: "4AM-9PM", month: "June, July, August, September", type:"Fish"},
  {'name': "Gar", price: "6000", location: "Pond", time: "4PM-9AM", month: "June, July, August, September", type:"Fish"},
  {'name': "Arapaima", price: "10000", location: "River", time: "4PM-9AM", month: "June, July, August, September", type:"Fish"},
  {'name': "Saddled Bichir", price: "4000", location: "River", time: "9PM-4AM", month: "June, July, August, September", type:"Fish"},
  {'name': "Sturgeon", price: "10000", location: "River (mouth)", time: "All", month: "January, February, March, September, October, November, December", type:"Fish"},
  {'name': "Sea Butterfly", price: "1000", location: "Sea", time: "All", month: "January, February, March, December", type:"Fish"},
  {'name': "Sea Horse", price: "1100", location: "Sea", time: "All", month: "April, May, June, July, August, September, October, November", type:"Fish"},
  {'name': "Clown Fish", price: "650", location: "Sea", time: "All", month: "April, May, June, July, August, September", type:"Fish"},
  {'name': "Surgeonfish", price: "1000", location: "Sea", time: "All", month: "April, May, June, July, August, September", type:"Fish"},
  {'name': "Butterfly Fish", price: "1000", location: "Sea ", time: "All", month: "April, May, June, July, August, September", type:"Fish"},
  {'name': "Napoleonfish", price: "10000", location: "Sea", time: "4AM-9PM", month: "July, August", type:"Fish"},
  {'name': "Zebra Turkeyfish", price: "500", location: "Sea", time: "All", month: "April, May, June, July, August, September, October, November", type:"Fish"},
  {'name': "Blowfish", price: "5000", location: "Sea", time: "9PM-4AM", month: "January, February, November, December", type:"Fish"},
  {'name': "Puffer Fish", price: "250", location: "Sea", time: "All", month: "July, August, September", type:"Fish"},
  {'name': "Anchovy", price: "200", location: "Sea", time: "4AM-9PM", month: "All", type:"Fish"},
  {'name': "Horse Mackerel", price: "150", location: "Sea", time: "All", month: "All", type:"Fish"},
  {'name': "Barred Knifejaw", price: "5000", location: "Sea", time: "All", month: "March, April, May, June, July, August, September, October, November", type:"Fish"},
  {'name': "Sea Bass", price: "400", location: "Sea", time: "All", month: "All", type:"Fish"},
  {'name': "Red Snapper", price: "3000", location: "Sea", time: "All", month: "All", type:"Fish"},
  {'name': "Dab", price: "300", location: "Sea", time: "All", month: "January, February, March, April, October, November, December", type:"Fish"},
  {'name': "Olive Flounder", price: "800", location: "Sea", time: "All", month: "All", type:"Fish"},
  {'name': "Squid", price: "500", location: "Sea", time: "All", month: "January, February, March, April, May, June, July, August, December", type:"Fish"},
  {'name': "Moray Eel", price: "2000", location: "Sea", time: "All", month: "August, September, October", type:"Fish"},
  {'name': "Ribbon Eel", price: "600", location: "Sea", time: "All", month: "June, July, August, September, October", type:"Fish"},
  {'name': "Tuna", price: "7000", location: "Pier", time: "All", month: "January, February, March, April, November, December", type:"Fish"},
  {'name': "Blue Marlin ", price: "10000", location: "Pier", time: "All", month: "January, February, March, April, July, August, September, November, December", type:"Fish"},
  {'name': "Giant Trevally", price: "4500", location: "Pier", time: "All", month: "May, June, July, August, September, October", type:"Fish"},
  {'name': "Mahi-mahi", price: "6000", location: "Pier", time: "All", month: "May, June, July, August, September, October", type:"Fish"},
  {'name': "Ocean Sunfish", price: "4000", location: "Sea", time: "4AM-9PM", month: "July, August, September", type:"Fish"},
  {'name': "Ray", price: "3000", location: "Sea", time: "4AM-9PM", month: "August, September, October, November", type:"Fish"},
  {'name': "Saw Shark", price: "12000", location: "Sea", time: "4PM-9AM", month: "June, July, August, September", type:"Fish"},
  {'name': "Hammerhead Shark", price: "8000", location: "Sea", time: "4PM-9AM", month: "June, July, August, September", type:"Fish"},
  {'name': "Great White Shark", price: "15000", location: "Sea", time: "4PM-9AM", month: "June, July, August, September", type:"Fish"},
  {'name': "Whale Shark", price: "13000", location: "Sea", time: "All", month: "June, July, August, September", type:"Fish"},
  {'name': "Suckerfish", price: "1500", location: "Sea", time: "All", month: "June, July, August, September", type:"Fish"},
  {'name': "Football Fish", price: "2500", location: "Sea", time: "4PM-9AM", month: "January, February, March, November, December", type:"Fish"},
  {'name': "Oarfish", price: "9000", location: "Sea", time: "All", month: "January, February, March, April, May, December", type:"Fish"},
  {'name': "Barreleye", price: "15000", location: "Sea", time: "9PM-4AM", month: "All", type:"Fish"},
  {'name': "Coelacanth", price: "15000", location: "Sea (rainy day)", time: "All", month: "All", type:"Fish"}
];

const bugData = [
  {'name': "Common Butterfly", price: "160", month: "January, February, March, April, May, June, September, October, November, December", time: "4AM-7PM", location: "Flying around", type:"Bug"},
  {'name': "Yellow Butterfly", price: "160", month: "March, April, May, June, September, October", time: "4AM-7PM", location: "Flying around", type:"Bug"},
  {'name': "Tiger Butterfly", price: "240", month: "March, April, May, June, July, August, September", time: "4AM-7PM", location: "Flying around", type:"Bug"},
  {'name': "Peacock Butterfly", price: "2500", month: "March, April, May, June", time: "4AM-7PM", location: "Flying around \"rare flowers\"", type:"Bug"},
  {'name': "Common Bluebottle", price: "300", month: "April, May, June, July, Aug", time: "4AM-7PM", location: "Flying around", type:"Bug"},
  {'name': "Paper Kite Butterfly", price: "1000", month: "All", time: "8AM-7PM", location: "Flying around ", type:"Bug"},
  {'name': "Great Purple Emperor", price: "3000", month: "May, June, July, Aug", time: "4AM-7PM", location: "Flying around", type:"Bug"},
  {'name': "Monarch Butterfly", price: "140", month: "September, October, November", time: "N/A", location: "Flying around", type:"Bug"},
  {'name': "Emperor Butterfly ", price: "4000", month: "January, February, March, June, July, August, September, December", time: "5PM-8AM", location: "Flying around ", type:"Bug"},
  {'name': "Agrias Butterfly", price: "3000", month: "April, May, June, July, August, September", time: "8AM-5PM", location: "Flying around ", type:"Bug"},
  {'name': "Rajah Brooke's Birdwing", price: "2500", month: "January, February, April, May, June, July, August, September, December", time: "8AM-5PM", location: "Flying around ", type:"Bug"},
  {'name': "Queen Alexandra's Birdwing", price: "4000", month: "May, June, July, August, September", time: "8AM-4PM", location: "Flying around ", type:"Bug"},
  {'name': "Moth", price: "130", month: "All", time: "7PM-4AM", location: "Buzzing around lamps and lights outside (there's usually one next to Residential Services)", type:"Bug"},
  {'name': "Atlas Moth", price: "3000", month: "April, May, June, July, August, September", time: "7PM-4AM", location: "On the side of trees", type:"Bug"},
  {'name': "Madagascan Sunset Moth", price: "2500", month: "April, May, June, July, August, September", time: "8AM-4PM", location: "Flying around", type:"Bug"},
  {'name': "Long Locust", price: "200", month: "April, May, June, July, August, September, October, November", time: "8AM-7PM", location: "Hopping on the floor", type:"Bug"},
  {'name': "Migratory Locust", price: "600", month: "August, September, October, November", time: "8AM-7PM", location: "Hopping on the floor", type:"Bug"},
  {'name': "Rice Grasshopper", price: "160", month: "August, September, October, November", time: "8AM-7PM", location: "Hopping on the floor", type:"Bug"},
  {'name': "Grasshopper", price: "160", month: "July, August, September", time: "8AM-5PM", location: "Hopping on the floor", type:"Bug"},
  {'name': "Cricket", price: "130", month: "September, October, November", time: "5PM-8AM", location: "Hopping on the floor", type:"Bug"},
  {'name': "Bell Cricket", price: "430", month: "September, October", time: "5PM-8AM", location: "Hopping on the floor", type:"Bug"},
  {'name': "Mantis", price: "430", month: "March, April, May, June, July, August, September, October, November", time: "8AM-5PM", location: "Praying on flowers ", type:"Bug"},
  {'name': "Orchid Mantis", price: "2400", month: "March, April, May, June, July, August, September, October, November", time: "8AM-5PM", location: "Praying on white flowers", type:"Bug"},
  {'name': "Honeybee", price: "200", month: "March, April, May, June, July", time: "8AM-5PM", location: "Flying around", type:"Bug"},
  {'name': "Wasp", price: "2500", month: "All ", time: "All", location: "Catch in net when they attack you after shaking or chopping a tree", type:"Bug"},
  {'name': "Brown Cicada", price: "", month: "July, August", time: "8AM-5PM", location: "On the side of trees", type:"Bug"},
  {'name': "Robust Cicada", price: "", month: "July, August", time: "8AM-5PM", location: "On the side of trees", type:"Bug"},
  {'name': "Giant Cicada", price: "", month: "July, August", time: "8AM-5PM", location: "On the side of trees", type:"Bug"},
  {'name': "Walker Cicada", price: "400", month: "August, September", time: "8AM-5PM", location: "On the side of trees", type:"Bug"},
  {'name': "Evening Cicada", price: "", month: "July, August", time: "4AM-8AM, 4PM-7PM", location: "On the side of trees", type:"Bug"},
  {'name': "Cicada Shell", price: "", month: "July, August", time: "All", location: "On the side of trees", type:"Bug"},
  {'name': "Red Dragonfly", price: "180", month: "September, October", time: "8AM-7PM", location: "Flying around", type:"Bug"},
  {'name': "Darner Dragonfly", price: "230", month: "April, May, June, July, August, September, October", time: "8AM-5PM", location: "Flying around", type:"Bug"},
  {'name': "Banded Dragonfly", price: "4500", month: "May, June, July, August, September, October", time: "8AM-5PM", location: "Flying around", type:"Bug"},
  {'name': "Damselfly", price: "", month: "January, February, November, December", time: "All", location: "Flying around", type:"Bug"},
  {'name': "Firefly", price: "", month: "June", time: "7PM-4AM", location: "Flying around", type:"Bug"},
  {'name': "Mole Cricket", price: "500", month: "January, February, March, April, May, November, December", time: "All", location: "Dig underground", type:"Bug"},
  {'name': "Pondskater", price: "130", month: "May, June, July, August, September", time: "8AM-7PM", location: "Scooting on the top of rivers and ponds", type:"Bug"},
  {'name': "Diving Beetle", price: "800", month: "May, June, July, August, September", time: "8AM-7PM", location: "Scooting on the top of rivers and ponds", type:"Bug"},
  {'name': "Giant Water Bug", price: "2000", month: "April, May, June, July, August, September", time: "7PM-8AM", location: "Scooting on the top of rivers and ponds", type:"Bug"},
  {'name': "Stinkbug", price: "120", month: "March, April, May, June, July, August, September, October", time: "All", location: "In bunches of flowers", type:"Bug"},
  {'name': "Man-faced Stink Bug", price: "1000", month: "March, April, May, June, July, August, September, October", time: "7PM-8AM", location: "In bunches of flowers", type:"Bug"},
  {'name': "Ladybug", price: "200", month: "March, April, May, June, October", time: "8AM-5PM", location: "In bunches of flowers", type:"Bug"},
  {'name': "Tiger Beetle", price: "1500", month: "February, March, April, May, June, July, August, September, October", time: "All", location: "Crawling on the floor", type:"Bug"},
  {'name': "Jewel Bettle", price: "2400", month: "April, May, June, July, August", time: "All", location: "Spawns on chopped tree stumps (use axe, not stone axe, to chop down)", type:"Bug"},
  {'name': "Violin Beetle", price: "450", month: "May, June, September, October, November", time: "All", location: "Spawns on chopped tree stumps (use axe, not stone axe, to chop down)", type:"Bug"},
  {'name': "Citrus Long-horned Beetle", price: "350", month: "All", time: "All", location: "Spawns on chopped tree stumps (use axe, not stone axe, to chop down)", type:"Bug"},
  {'name': "Rosalia Batesi Beetle", price: "3000", month: "May, June, July, August, September", time: "All", location: "Spawns on chopped tree stumps (use axe, not stone axe, to chop down)", type:"Bug"},
  {'name': "Blue Weevil Beetle", price: "", month: "July, August", time: "All", location: "", type:"Bug"},
  {'name': "Earth-boring Dung Beetle", price: "300", month: "July, August, September", time: "All", location: "Rolling balls of dung around", type:"Bug"},
  {'name': "Dung Beetle", price: "", month: "January, February, December", time: "All", location: "Rolling balls of dung around", type:"Bug"},
  {'name': "Scarab Beetle", price: "", month: "July, August", time: "11PM-8AM", location: "On the side of trees", type:"Bug"},
  {'name': "Drone Beetle", price: "", month: "June, July, August", time: "All", location: "On the side of trees", type:"Bug"},
  {'name': "Goliath Beetle", price: "8000", month: "June, July, August, September", time: "5PM-8AM", location: "On the side of palm trees", type:"Bug"},
  {'name': "Saw Stag", price: "", month: "July, August", time: "All", location: "On the side of trees", type:"Bug"},
  {'name': "Miyama Stag ", price: "", month: "July, August", time: "All", location: "On the side of trees", type:"Bug"},
  {'name': "Giant Stag", price: "10000", month: "July, August", time: "11PM-8AM", location: "On the side of trees", type:"Bug"},
  {'name': "Rainbow Stag", price: "6000", month: "June, July, August, September", time: "7PM-8AM", location: "On the side of trees", type:"Bug"},
  {'name': "Cyclommatus Stag", price: "", month: "July, August", time: "5PM-8AM", location: "On the side of trees", type:"Bug"},
  {'name': "Golden Stag", price: "", month: "July, August", time: "5PM-8AM", location: "On the side of trees", type:"Bug"},
  {'name': "Giraffe Stag", price: "", month: "July, August", time: "5PM-8AM", location: "On the side of trees", type:"Bug"},
  {'name': "Horned Dynastid", price: "", month: "July, August", time: "5PM-8AM", location: "On the side of trees", type:"Bug"},
  {'name': "Horned Atlas", price: "", month: "July, August", time: "5PM-8AM", location: "On the side of trees", type:"Bug"},
  {'name': "Horned Elephant", price: "", month: "July, August", time: "5PM-8AM", location: "On the side of trees", type:"Bug"},
  {'name': "Horned Hercules", price: "", month: "July, August", time: "5PM-8AM", location: "On the side of trees", type:"Bug"},
  {'name': "Walking Stick", price: "", month: "July, August, September, October, November", time: "4AM-8AM, 5PM-7PM", location: "Falls out of shaken trees", type:"Bug"},
  {'name': "Walking Leaf", price: "600", month: "July, August, September", time: "All", location: "Underneath trees", type:"Bug"},
  {'name': "Bagworm", price: "600", month: "All", time: "All", location: "Falls out of shaken trees", type:"Bug"},
  {'name': "Ant", price: "", month: "All ", time: "All", location: "On rotten food on the floor", type:"Bug"},
  {'name': "Hermit Crab", price: "1000", month: "All ", time: "7PM-8AM", location: "Looks like a shell but runs away when you get close", type:"Bug"},
  {'name': "Wharf Roach", price: "200", month: "All", time: "All", location: "On rocks on the beach", type:"Bug"},
  {'name': "Fly", price: "60", month: "All ", time: "All", location: "Buzzing around rubbish", type:"Bug"},
  {'name': "Mosquito", price: "130", month: "June, July, August, September", time: "5PM-4AM", location: "Flying around", type:"Bug"},
  {'name': "Flea", price: "", month: "April, May, June, July, August, September, October, November", time: "All", location: "Bouncing on certain villager's heads", type:"Bug"},
  {'name': "Snail", price: "250", month: "All", time: "All", location: "On rocks when it's raining", type:"Bug"},
  {'name': "Pill Bug", price: "250", month: "January, February, March, April, May, June, September, October, November, December", time: "11PM-4PM", location: "Crawls from under rocks when you hit them", type:"Bug"},
  {'name': "Centipede", price: "300", month: "January, February, March, April, May, June, September, October, November, December", time: "4PM-11PM", location: "Crawls from under rocks when you hit them", type:"Bug"},
  {'name': "Spider", price: "480", month: "All", time: "7PM-8AM", location: "Shake trees at night", type:"Bug"},
  {'name': "Tarantula", price: "8000", month: "January, February, March, April, November, December", time: "7PM-4AM", location: "Scurrying around the floor at night - attacks you", type:"Bug"},
  {'name': "Scorpion", price: "8000", month: "May, June, July, August, September, October, ", time: "7PM-4AM", location: "Scurrying around the floor at night - attacks you", type:"Bug"},
];

const paintingData = [
  {'name': "Serene Painting", location: "The real version will have a woman holding an all-white ermine. In the fake version, the ermine will have raccoon-like circles around its eyes", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Warm Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Wistful Painting", location: "The real version has a pearl earring. The fake version has a star-shaped earring", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Academic Painting", location: "The fake version of this painting will have a coffee stain in the corner", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Graceful Painting", location: "The real version has a white tag near her hair. The fake version does not have the tag. The woman in the fake painting is also larger. Another version of a fake Graceful Painting has her looking to the left, instead of to the right", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Calm Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Flowery Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Jolly Painting", location: "The fake Jolly Painting will be missing the sprout on the subject’s chest", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Moody Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Famous Painting", location: "The fake Famous Painting will have eyebrows", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Scary Painting", location: "The fake Scary Painting will have sad-looking eyebrows. The real one looks more angry", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Dynamic Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Scenic Painting", location: "The fake version of the Scenic Painting will be missing a hunter and some dogs. Real has 2 hunters and 11 dogs", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Moving Painting", location: "The fake version of the Moving Painting will be missing trees in the top right corner", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Amazing Painting", location: "The man in the front of the fake Amazing Painting is missing his hat", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Quaint Painting", location: "In the fake version, the woman in the Quaint Painting is pouring out much more milk than she is in the real version", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Solemn Painting", location: "The man in the background of the fake Solemn Painting is raising his arm more than he is in the real version", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Basic Painting", location: "The fake version of the Basic Painting depicts the boy with more hair", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Worthy Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Glowing Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Common Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Sinking Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Nice Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Proper Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Mysterious Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Twinkling Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Perfect Painting", location: "Always genuine", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Wild Painting Left Half", location: "In the fake version of the Wild Painting Left Half, the beast is green. It should be white", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Wild Painting Right Half", location: "In the fake version of the Wild Painting Right Half, the beast is white. It should be green", month: "All", time: "All", price: "", type:"Painting"},
  {'name': "Detailed Painting", location: "The fake Detailed Painting has purple foliage instead of blue. It’s also missing a signature on the left", month: "All", time: "All", price: "", type:"Painting"},
];

const statueData = [
  {'name': "Warrior Statue", location: "The real version will not be holding anything. The fake version is holding a shovel", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Motherly Statue", location: "The fake version of the Motherly Statue will have a tongue sticking out of the wolf’s mouth", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Beautiful Statue", location: "The fake version will be wearing a necklace", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Familiar Statue", location: "Always genuine", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Robust Statue", location: "The fake statue will be wearing a watch on his raised arm", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Gallant Statue", location: "The fake statue is holding a book under his arm", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Informative Statue", location: "The fake Informative Statue will be blue, but the real one is black", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Rock-head Statue", location: "The fake statue will be smiling", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Ancient Statue", location: "The fake Ancient Statue has two antennas coming out of the side of its head", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Tremendous Statue", location: "The fake version of this statue has a lid. The real one will be open at the top", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Valiant Statue", location: "The fake version of this statue will have Nike’s left leg forward. The real version has her right leg forward", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Mystic Statue", location: "The fake Mystic Statue will have an earring on the subject’s right ear. Facing the statue directly, the earring will be on the viewer’s left", month: "All", time: "All", price: "", type:"Statue"},
  {'name': "Great Statue", location: "Always genuine", month: "All", time: "All", price: "", type:"Statue"},
];

const plantData = [
  //Roses
  {'name': "Red Rose", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "White Rose", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Yellow Rose", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Orange Rose", price: "", month: "All", time: "All", location: "50% Red x Yellow", type:"Plant"},
  {'name': "Black Rose", price: "", month: "All", time: "All", location: "25% Red x Red", type:"Plant"},
  {'name': "Pink Rose", price: "", month: "All", time: "All", location: "25% Red x Red, 50% Red x White", type:"Plant"},
  {'name': "Purple Rose", price: "", month: "All", time: "All", location: "25% White x White", type:"Plant"},
  {'name': "Blue Rose", price: "", month: "All", time: "All", location: "6.25% Orange x Orange", type:"Plant"},
  {'name': "Gold Rose", price: "", month: "All", time: "All", location: "50% chance when watering a black rose with a golden watering can", type:"Plant"},
 
  //Tulips 
  {'name': "Red Tulip", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "White Tulip", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Yellow Tulip", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Orange Tulip", price: "", month: "All", time: "All", location: "50% Red x Yellow", type:"Plant"},
  {'name': "Black Tulip", price: "", month: "All", time: "All", location: "25% Red x Red, 19% Orange x Orange", type:"Plant"},
  {'name': "Pink Tulip", price: "", month: "All", time: "All", location: "50% Red x White", type:"Plant"},
  {'name': "Purple Tulip", price: "", month: "All", time: "All", location: "6% Orange x Orange", type:"Plant"},
 
  //Pansies 
  {'name': "Red Pansy", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "White Pansy", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Yellow Pansy", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Orange Pansy", price: "", month: "All", time: "All", location: "100% Red x Yellow", type:"Plant"},
  {'name': "Blue Pansy", price: "", month: "All", time: "All", location: "25% White x White, 19% Red(hybrid) x Red(hybrid)", type:"Plant"},
  {'name': "Red(hybrid) Pansy", price: "", month: "All", time: "All", location: "100% Blue x Red", type:"Plant"},
  {'name': "Purple Pansy", price: "", month: "All", time: "All", location: "6% Red(hybrid) x Red(hybrid)", type:"Plant"},
 
  //Cosmos
  {'name': "Red Cosmos", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "White Cosmos", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Yellow Cosmos", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Orange Cosmos", price: "", month: "All", time: "All", location: "100% Red x Yellow", type:"Plant"},
  {'name': "Pink Cosmos", price: "", month: "All", time: "All", location: "100% Red x White", type:"Plant"},
  {'name': "Black Cosmos", price: "", month: "All", time: "All", location: "6% Orange x Orange", type:"Plant"},
 
  //Lilies
  {'name': "Red Lily", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "White Lily", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Yellow Lily", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Orange Lily", price: "", month: "All", time: "All", location: "50% Red x Yellow", type:"Plant"},
  {'name': "Pink Lily", price: "", month: "All", time: "All", location: "25% Red x Red, 50% Red x White", type:"Plant"},
  {'name': "Black Lily", price: "", month: "All", time: "All", location: "25% Red x Red", type:"Plant"},
 
  //Hyacinths
  {'name': "Red Hyacinth", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "White Hyacinth", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Yellow Hyacinth", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Orange Hyacinth", price: "", month: "All", time: "All", location: "50% Red x Yellow", type:"Plant"},
  {'name': "Pink Hyacinth", price: "", month: "All", time: "All", location: "50% Red x White", type:"Plant"},
  {'name': "Purple Hyacinth", price: "", month: "All", time: "All", location: "6% Orange x Orange", type:"Plant"},
  {'name': "Blue Hyacinth", price: "", month: "All", time: "All", location: "25% White x White, 13% Orange x Orange", type:"Plant"},
  
  //Windflower
  {'name': "Red Windflower", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "White Windflower", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Orange Windflower", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Pink Windflower", price: "", month: "All", time: "All", location: "100% Red x Orange", type:"Plant"},
  {'name': "Red(hybrid) Windflower", price: "", month: "All", time: "All", location: "100% Blue x Red", type:"Plant"},
  {'name': "Purple Windflower", price: "", month: "All", time: "All", location: "6% Red(hybrid) x Red(hybrid)", type:"Plant"},
  {'name': "Blue Windflower", price: "", month: "All", time: "All", location: "25% White x White", type:"Plant"},
 
  //Mums
  {'name': "Red Mum", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "White Mum", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Yellow Mum", price: "", month: "All", time: "All", location: "", type:"Plant"},
  {'name': "Yellow(hybrid) Mum", price: "", month: "All", time: "All", location: "100% Red x Yellow", type:"Plant"},
  {'name': "Pink Mum", price: "", month: "All", time: "All", location: "100% Red x White, 13% Yellow(hybrid) x Yellow(hybrid)", type:"Plant"},
  {'name': "Purple Mum", price: "", month: "All", time: "All", location: "25% White x White, 26% Yellow(hybrid) x Yellow(hybrid)", type:"Plant"},
  {'name': "Green Mum", price: "", month: "All", time: "All", location: "25% Purple x Purple, 6% Yellow(hybrid) x Yellow(hybrid)", type:"Plant"},
];

const fossilData = [
  {'name': "Acanthostega", price: "2000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Amber", price: "1200", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Ammonite", price: "1100", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Anomalocaris", price: "2000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Archaeopteryx", price: "1300", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Australopith", price: "1100", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Coprolite", price: "1100", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Dinosaur track", price: "1000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Dunkleosteus", price: "3500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Eusthenopteron", price: "2000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Juramaia", price: "1000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Myllokunmingia", price: "1500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Shark-tooth pattern", price: "1000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Trilobite", price: "1300", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Ankylo skull", price: "3500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Ankylo torso", price: "3000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Ankylo tail", price: "2500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Archelon skull", price: "4000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Archelon tail", price: "3500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Brachio skull", price: "6000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Brachio chest", price: "5500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Brachio pelvis", price: "5000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Brachio tail", price: "5500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Deinony torso", price: "3000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Deinony tail", price: "2500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Dimetrodon skull", price: "5500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Dimetrodon torso", price: "5000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Diplo skull", price: "5000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Diplo neck", price: "4500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Diplo chest", price: "4000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Diplo pelvis", price: "4500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Diplo tail", price: "5000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Diplo tail tip", price: "4000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Iguanodon skull", price: "4000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Iguanodon torso", price: "3500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Iguanodon tail", price: "3000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Mammoth skull", price: "3000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Mammoth torso", price: "2500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Megacero skull", price: "4500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Megacero torso", price: "3500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Megacero tail", price: "3000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Left megalo side", price: "4000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Right megalo side", price: "5500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Ophthalmo skull", price: "2500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Ophthalmo torso", price: "2000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Pachy skull", price: "4000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Pachy tail", price: "3500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Parasaur skull", price: "3500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Parasaur torso", price: "3000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Parasaur tail", price: "2500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Plesio skull", price: "4000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Plesio tail", price: "4500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Plesio torso", price: "4500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Right ptera wing", price: "4500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Ptera body", price: "4000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Left ptera wing", price: "4500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Right quetzal wing", price: "5000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Quetzal torso", price: "4500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Left quetzal wing", price: "5000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Sabertooth skull", price: "2500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Sabertooth tail", price: "2000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Spino skull", price: "4000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Spino torso", price: "5000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Spino tail", price: "2500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Stego skull", price: "5000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Stego torso", price: "4500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Stego tail", price: "4000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Tricera skull", price: "5500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Tricera torso", price: "5000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "Tricera tail", price: "4500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "T. rex skull", price: "6000", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "T. rex torso", price: "5500", month: "All", time: "All", location: "", type:"Fossil"},
  {'name': "T. rex tail", price: "5000", month: "All", time: "All", location: "", type:"Fossil"},
];

const seacreaturesData = [
  {'name': "Seaweed", price: "600", location: "Shadow: Large", time: "All", month: "January, February, March, April, May, June, July, October, November, December", type:"Sea Creature"},
  {'name': "Sea Grapes", price: "900", location: "Shadow: Small", time: "All", month: "June, July, August, September", type:"Sea Creature"},
  {'name': "Sea Cucumber", price: "500", location: "Shadow: Medium", time: "All", month: "January, February, March, April, November, December", type:"Sea Creature"},
  {'name': "Sea Pig", price: "10000", location: "Shadow: Small", time: "4PM-9AM", month: "January, February, November, December", type:"Sea Creature"},
  {'name': "Sea Star", price: "500", location: "Shadow: Small", time: "All", month: "All", type:"Sea Creature"},
  {'name': "Sea Urchin", price: "1700", location: "Shadow: Small", time: "All", month: "May, June, July, August, September", type:"Sea Creature"},
  {'name': "Slate Pencil Urchin", price: "2000", location: "Shadow: Medium", time: "4PM-9AM", month: "May, June, July, August, September", type:"Sea Creature"},
  {'name': "Sea Anemone", price: "500", location: "Shadow: Large", time: "All", month: "All", type:"Sea Creature"},
  {'name': "Moon Jellyfish", price: "600", location: "Shadow: Small", time: "All", month: "July, August, September", type:"Sea Creature"},
  {'name': "Sea Slug", price: "600", location: "Shadow: Tiny", time: "All", month: "All", type:"Sea Creature"},
  {'name': "Pearl Oyster", price: "2800", location: "Shadow: Small", time: "All", month: "All", type:"Sea Creature"},
  {'name': "Mussel", price: "1500", location: "Shadow: Small", time: "All", month: "June, July, August, September, October, November, December", type:"Sea Creature"},
  {'name': "Oyster", price: "1100", location: "Shadow: Small", time: "All", month: "January, February, September, October, November, December", type:"Sea Creature"},
  {'name': "Scallop", price: "1200", location: "Shadow: Medium", time: "All", month: "All", type:"Sea Creature"},
  {'name': "Whelk", price: "1000", location: "Shadow: Small", time: "All", month: "All", type:"Sea Creature"},
  {'name': "Turban Shell", price: "1000", location: "Shadow: Small", time: "All", month: "March, April, May, September, October, November, December", type:"Sea Creature"},
  {'name': "Abalone", price: "2000", location: "Shadow: Medium", time: "4PM-9AM", month: "January, June, July, August, September, October, November, December", type:"Sea Creature"},
  {'name': "Gigas Giant Clam", price: "15000", location: "Shadow: Huge", time: "All", month: "May, June, July, August, September", type:"Sea Creature"},
  {'name': "Chambered Nautilus", price: "1800", location: "Shadow: Medium", time: "4PM-9AM", month: "March, April, May, June, September, October, November", type:"Sea Creature"},
  {'name': "Octopus", price: "1200", location: "Shadow: Medium", time: "All", month: "All", type:"Sea Creature"},
  {'name': "Umbrella Octopus", price: "6000", location: "Shadow: Small", time: "All", month: "March, April, May, September, October, November", type:"Sea Creature"},
  {'name': "Vampire Squid", price: "10000", location: "Shadow: Medium", time: "5PM-9AM", month: "May, June, July, August", type:"Sea Creature"},
  {'name': "Firefly Squid", price: "1400", location: "Shadow: Tiny", time: "9PM-4AM", month: "March, April, May, June", type:"Sea Creature"},
  {'name': "Gazami Crab", price: "2200", location: "Shadow: Medium", time: "All", month: "June, July, August, September, October, November", type:"Sea Creature"},
  {'name': "Dungeness Crab", price: "1900", location: "Shadow: Medium", time: "All", month: "January, February, March, April, May, November, December", type:"Sea Creature"},
  {'name': "Snow Crab", price: "6000", location: "Shadow: Large", time: "All", month: "January, February, March, April, November, December", type:"Sea Creature"},
  {'name': "Red King Crab", price: "8000", location: "Shadow: Large", time: "All", month: "January, February, March, November, December", type:"Sea Creature"},
  {'name': "Acorn Barnacle", price: "600", location: "Shadow: Tiny", time: "All", month: "All", type:"Sea Creature"},
  {'name': "Spider Crab", price: "12000", location: "Shadow: Huge", time: "All", month: "March, April", type:"Sea Creature"},
  {'name': "Tiger Prawn", price: "3000", location: "Shadow: Small", time: "4PM-9AM", month: "June, July, August, September", type:"Sea Creature"},
  {'name': "Sweet Shrimp", price: "1400", location: "Shadow: Small", time: "4PM-9AM", month: "January, February, September, October, November, December", type:"Sea Creature"},
  {'name': "Mantis Shrimp", price: "2500", location: "Shadow: Small", time: "4PM-9AM", month: "All", type:"Sea Creature"},
  {'name': "Spiny Lobster", price: "5000", location: "Shadow: Large", time: "9PM-4AM", month: "October, November, December", type:"Sea Creature"},
  {'name': "Lobster", price: "4500", location: "Shadow: Large", time: "All", month: "January, April, May, June, December", type:"Sea Creature"},
  {'name': "Giant Isopod", price: "12000", location: "Shadow: Medium", time: "9AM-4PM, 9PM-4AM", month: "July, August, September, October", type:"Sea Creature"},
  {'name': "Horseshoe Crab", price: "2500", location: "Shadow: Medium", time: "9PM-4AM", month: "July, August, September", type:"Sea Creature"},
  {'name': "Sea Pineapple", price: "1500", location: "Shadow: Small", time: "All", month: "April, May, June, July, August", type:"Sea Creature"},
  {'name': "Spotted Garden Eel", price: "1100", location: "Shadow: Small", time: "4AM-9PM", month: "May, June, July, August, September, October", type:"Sea Creature"},
  {'name': "Flatworm", price: "700", location: "Shadow: Tiny", time: "4PM-9AM", month: "August, September", type:"Sea Creature"},
  {'name': "Venus Flower Basket", price: "5000", location: "Shadow: Medium", time: "All", month: "January, February, October, November, December", type:"Sea Creature"},
];